{% set version = "1.3.6" %}
{% set build_number = "1" %}

package:
  name: basemap-split
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}.tar.gz
  sha256: 42adbd039b4afbe93ca2fa32cfab456d4fd590cb8ed1c28e4aa94dcb957b58ac
  patches:
    # Update messages regarding installation of `basemap-data-hires`.
    - install_hires_instructions.patch
    - install_numpy_override.patch         # <--- This is a horible hack. Remove ASAP.

build:
  number: {{ build_number }}
  skip: True  # [py<37]
  skip: True  # [s390x]  Missing dependencies.
  skip: True  # [win32]  Missing dependencies in win32 arch and not expecting they will be updated.

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]

outputs:
  - name: basemap
    script: build-basemap.sh  # [not win]  This script will delete `pyproject.toml`. Remove ASAP.
    script: bld-basemap.bat   # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pip
        - cython >=0.29,<3.1
        - numpy 1.21  # [(py<310 and not ppc64le) or py==310]
        - numpy 1.22  # [py>=311]
        - numpy 1.19  # [ppc64le and py<310]
        - geos
        - pyproj
        - setuptools <61  # [win]
        - setuptools      # [not win]
        - wheel
      run:
        - {{ pin_subpackage('basemap-data') }}
        - python
        - {{ pin_compatible('numpy') }}
        - {{ pin_compatible('geos') }}
        - matplotlib-base >=1.5,!=3.0.1,<3.7
        - pyproj >=1.9.3,<3.5.0
        - pyshp >=1.2.0,<2.4
    test:
      imports:
        - mpl_toolkits.basemap
      requires:
        - pip
        - {{ pin_subpackage('basemap-data') }}
        - python <3.11  # [py<311]
        - python        # [py>=311]
      commands:
        - pip check
        - python -c "from mpl_toolkits.basemap import Basemap"
    about:
      home: https://matplotlib.org/basemap
      license: MIT
      license_family: MIT
      license_file:
        - packages/basemap/LICENSE
      summary: 'Plot on map projections using matplotlib'
      description: |
        Basemap toolkit is a library for plotting 2D data on maps in Python.
        It is similar in functionality to the matlab mapping toolbox, the IDL mapping facilities, GrADS, or the Generic Mapping Tools.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/
      doc_source_url: https://github.com/matplotlib/basemap/blob/v{{ version }}/packages/basemap/doc/index.rst

  - name: basemap-data
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools <61  # [win]
        - setuptools  # [not win]
        - wheel
      run:
        - python
    test:
      requires:
        - python <3.11  # [py<311]
        - python        # [py>=311]

    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: packages/basemap_data_hires/COPYING.LESSER
      summary: Plot on map projections (with coastlines and political boundaries) using matplotlib.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/
      doc_source_url: https://github.com/matplotlib/basemap/blob/v{{ version }}/packages/basemap/doc/index.rst

  - name: basemap-data-hires
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools <61  # [win]
        - setuptools  # [not win]
        - wheel
      run:
        - {{ pin_subpackage('basemap-data') }}
        - python
    test:
      requires:
        - python <3.11  # [py<311]
        - python        # [py>=311]
    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: packages/basemap_data_hires/COPYING.LESSER
      summary: Plot on map projections (with coastlines and political boundaries) using matplotlib.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/

extra:
  recipe-maintainers:
    - molinav
    - ocefpaf
