{% set version = "1.1.0" %}

package:
  name: basemap
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}.tar.gz
  sha256: 6acdc3a08bfcebf0a1b52a05d73d51b7aa5e7240fedfa95537c92d16f2ef8778
  patches:
    - basemap-1.0.8dev-datadir.patch

build:
  number: 0

requirements:
  build:
    - python
    - numpy x.x
    - geos 3.5.*
  run:
    - python
    - numpy x.x
    - geos 3.5.*
    - matplotlib
    - pyproj
    - pyshp

test:
  imports:
    - mpl_toolkits.basemap
  commands:
    - conda inspect linkages -p $PREFIX basemap  # [not win]
    - conda inspect objects -p $PREFIX basemap  # [osx]

about:
  home: http://matplotlib.org/basemap
  license: MIT
  license_file: README.md
  summary: 'Plot on map projections using matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
