{% set version = "1.4.1" %}
{% set build_number = "0" %}

# note:
# In truth, basemap-data and basemap-data-hiredis do not follow the same version as basemap.
# These packages should remain at 1.3.2. However we already have a 1.3.6 version published.
# So we'll keep the versions aligned.

package:
  name: basemap-split
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}.tar.gz
  sha256: 730b1e2ff5eb31c73680bd8ebabc6b11adfc587cfa6832c528a8a82822e5a490
  patches:
    # Update messages regarding installation of `basemap-data-hires`.
    - patches/install_hires_instructions.patch

build:
  number: {{ build_number }}
  skip: True  # [s390x]  Missing dependencies.

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]

outputs:
  - name: basemap
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python
        - pip
        - setuptools
        - wheel
        - cython >=0.29,<3.1
        - numpy {{ numpy }}
        - geos {{ geos }}
      run:
        - {{ pin_subpackage('basemap-data', min_pin='x.x.x', max_pin='x.x', exact=False) }}
        - python
        - {{ pin_compatible('numpy', upper_bound='1.27') }}
        - {{ pin_compatible('geos') }}
        - matplotlib-base >=1.5,<3.9
        - pyproj >=1.9.3,<3.7.0
        - pyshp >=1.2.0,<2.4
        - packaging >=16.0,<24.0
    test:
      imports:
        - mpl_toolkits.basemap
      requires:
        - pip
      commands:
        - pip check
        - python -c "from mpl_toolkits.basemap import Basemap"
    about:
      home: https://matplotlib.org/basemap
      license: MIT
      license_family: MIT
      license_file:
        - packages/basemap/LICENSE
      summary: 'Plot on map projections using matplotlib'
      description: |
        Basemap toolkit is a library for plotting 2D data on maps in Python.
        It is similar in functionality to the matlab mapping toolbox, the IDL mapping facilities, GrADS, or the Generic Mapping Tools.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/

  - name: basemap-data
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
    test:
      requires:
        - pip
      commands:
        - pip check

    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: packages/basemap_data_hires/COPYING.LESSER
      summary: Plot on map projections (with coastlines and political boundaries) using matplotlib.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/

  - name: basemap-data-hires
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - {{ pin_subpackage('basemap-data', min_pin='x.x.x', max_pin='x.x', exact=False) }}
        - python
    test:
      requires:
        - pip
      commands:
        - pip check
    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: packages/basemap_data_hires/COPYING.LESSER
      summary: Plot on map projections (with coastlines and political boundaries) using matplotlib.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/

extra:
  recipe-maintainers:
    - molinav
    - ocefpaf
