{% set version = "2.0.0" %}
{% set build_number = "0" %}

package:
  name: basemap-split
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}.tar.gz
  sha256: 192ee1c63291d7d1af98fab798c45239ea27e6ca31041afa8c42c8b697e44596
  patches:
    # Update messages regarding installation of `basemap-data-hires`.
    - patches/install_hires_instructions.patch

build:
  number: 0

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]

outputs:
  - name: basemap
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python
        - pip
        - setuptools >= 67.0,< 81.0
        - wheel >=0.40,< 0.46
        - cython >=3.0,<3.2
        - numpy {{ numpy }}
        - geos {{ geos }}
      run:
        - python
        - {{ pin_subpackage('basemap-data', min_pin='x.x.x', max_pin='x', exact=False) }}
        - packaging >=20.5,<26.0
        - numpy >=2.0,<2.4
        - matplotlib-base >=3.4,<3.11
        - pyproj >=3.0,<3.8
        - pyshp >=2.0,<2.4
        - geos # bounds through run_exports
    test:
      imports:
        - mpl_toolkits.basemap
      requires:
        - pip
      commands:
        - pip check
        - python -c "from mpl_toolkits.basemap import Basemap"
    about:
      home: https://matplotlib.org/basemap
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: 'Plot on map projections using matplotlib'
      description: |
        Basemap toolkit is a library for plotting 2D data on maps in Python.
        It is similar in functionality to the matlab mapping toolbox, the IDL mapping facilities, GrADS, or the Generic Mapping Tools.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/

  - name: basemap-data
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
    test:
      requires:
        - pip
      commands:
        - pip check

    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: data/basemap_data_hires/COPYING.LESSER
      summary: Plot on map projections (with coastlines and political boundaries) using matplotlib.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/

  - name: basemap-data-hires
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - {{ pin_subpackage('basemap-data', min_pin='x.x.x', max_pin='x.x', exact=False) }}
        - python
    test:
      requires:
        - pip
      commands:
        - pip check
    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: data/basemap_data_hires/COPYING.LESSER
      summary: Plot on map projections (with coastlines and political boundaries) using matplotlib.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/

extra:
  recipe-maintainers:
    - molinav
    - ocefpaf
