{% set version = "1.1.0" %}

package:
  name: basemap
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}.tar.gz
  sha256: 6acdc3a08bfcebf0a1b52a05d73d51b7aa5e7240fedfa95537c92d16f2ef8778
  patches:
    - basemap-1.0.8dev-datadir.patch
    - backport_386.patch

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos
    - matplotlib
    - pyproj
    - pyshp

test:
  imports:
    - mpl_toolkits.basemap
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://matplotlib.org/basemap
  license: MIT
  license_file: README.md
  summary: 'Plot on map projections using matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
