package:
    name: basemap
    version: 1.0.8.dev0

source:
  git_url: https://github.com/matplotlib/basemap.git
  git_tag: 116aefb
  patches:
      - basemap-1.0.8dev-datadir.patch

build:
    number: 2

requirements:
    build:
        - python
        - numpy x.x
        - geos 3.4.*
    run:
        - python
        - numpy x.x
        - geos 3.4.*
        - matplotlib
        - pyproj
        - pyshp

test:
    imports:
        - mpl_toolkits.basemap
    commands:
        - conda inspect linkages -n _test basemap  # [not win]
about:
    home: http://matplotlib.org/basemap
    license: MIT
    summary: 'Plot on map projections using matplotlib.'

extra:
    recipe-maintainers:
        - ocefpaf
