travis:
  secure:
    BINSTAR_TOKEN: lfQGHo8QU0Yn3oHa1x4RRpwEnzeNrGKu74cH4h2vrbu59yPvxwYnh899PbCnJzS0sDWDfTE1N5a9RZv5CXWt0Bmysxz+AzesF/HULB0g7Kxzyl2ff4zutZTlnFaUXleAeGo68/Cn0usyAYIUUaxwqriCTnoVqTAM8HtNyHLagGmVCWgCV+mfFWI2iv8k79txQvGsoVKCBmtVMfefQQdszpS5JNgrDDf/tkcKFmJqwaVkaPU/p0MjTizsZPFtlZiXdy/0iKlH+FpiyJMrYbGf8iyeeVs5GuOl4WOh4iHUjVuAdKHf96/Nvyo0zi0jc0q4ezkfyyOTdwIkBwU/HnE2sIm19J9mn6AcNi4niS8bE9C1n+78OqhnHBhj+MNovDqFY+5QLwxpRR2ehoNTYNH8txoKRTNT/wFLwBVTkcUdALIcgkVWoUPHsfazTXhnoDiOqV2l3e0U6BHrouNisP/sgLPzCmkHvcj1kelg360ckI9sHMJDpJMKHtoDSif+Au1ALgPNeNX0MqxnjSvd7YTSp04yLPo1fWTwtae9Fo2cMikTIpS7155Fu+dW6G9/lNbBjoBW4uDOPaOj6NpWy8ksHemLGcV+eDtBXAdqruR5Du8G5L6qDMxRA3ifFqLc7/v3IsNkZAaV2DmBLFEvN2s+ZZ3SjBG1Jk+4s4dbJOK4zSc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
